apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ndombre-vsteffen
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/vsteffen/argocd-ndombre-vsteffen.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    automated:
      prune: true
      selfHeal: false
