apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
- ingress-argocd.yml

## changes to config maps
namespace: argocd
patches:
- path: argocd-cm.yml
- path: argocd-cmd-params-cm.yml
