- name: Install server
  hosts: server
  tasks:

    - name: Install K3S as controller
      args:
        warn: false
      shell: 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip {{ k3s_ip["server"] }} --bind-address {{ k3s_ip["server"] }} --tls-san $HOSTNAME" sh -'

    - name: Install Helm
      args:
        warn: false
      shell:
        cmd: 'curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | PATH=/usr/local/bin:$PATH bash'

    - name: Copy chart files to server
      become: yes
      copy:
        src: "{{ chart_src_path }}"
        dest: "/srv"

    - name: Install Helm chart
      become: yes
      shell:
        cmd: 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml PATH=/usr/local/bin:$PATH helm install {{ chart_name }} /srv/{{ chart_name }}'