{{- range $app := .Values.apps }}
---

apiVersion: v1
kind: Service
metadata:
  name: "app-{{ $app.name }}"
spec:
  ports:
  - port: 80
    targetPort: {{ $.Values.deployment.container.port }}
    protocol: TCP
  selector:
    app: 'app-{{ $app.name }}'

{{- end }}
